/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoadmapsIndexRouteImport } from './routes/roadmaps/index'
import { Route as DiagramsIndexRouteImport } from './routes/diagrams/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as RoadmapsIdRouteImport } from './routes/roadmaps/$id'
import { Route as DiagramsIdRouteImport } from './routes/diagrams/$id'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ShareDiagramTokenRouteImport } from './routes/share/diagram.$token'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapsIndexRoute = RoadmapsIndexRouteImport.update({
  id: '/roadmaps/',
  path: '/roadmaps/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagramsIndexRoute = DiagramsIndexRouteImport.update({
  id: '/diagrams/',
  path: '/diagrams/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapsIdRoute = RoadmapsIdRouteImport.update({
  id: '/roadmaps/$id',
  path: '/roadmaps/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagramsIdRoute = DiagramsIdRouteImport.update({
  id: '/diagrams/$id',
  path: '/diagrams/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareDiagramTokenRoute = ShareDiagramTokenRouteImport.update({
  id: '/share/diagram/$token',
  path: '/share/diagram/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/chat': typeof ApiChatRoute
  '/diagrams/$id': typeof DiagramsIdRoute
  '/roadmaps/$id': typeof RoadmapsIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/account/': typeof AccountIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/diagrams/': typeof DiagramsIndexRoute
  '/roadmaps/': typeof RoadmapsIndexRoute
  '/share/diagram/$token': typeof ShareDiagramTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/chat': typeof ApiChatRoute
  '/diagrams/$id': typeof DiagramsIdRoute
  '/roadmaps/$id': typeof RoadmapsIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/account': typeof AccountIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/diagrams': typeof DiagramsIndexRoute
  '/roadmaps': typeof RoadmapsIndexRoute
  '/share/diagram/$token': typeof ShareDiagramTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/chat': typeof ApiChatRoute
  '/diagrams/$id': typeof DiagramsIdRoute
  '/roadmaps/$id': typeof RoadmapsIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/account/': typeof AccountIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/diagrams/': typeof DiagramsIndexRoute
  '/roadmaps/': typeof RoadmapsIndexRoute
  '/share/diagram/$token': typeof ShareDiagramTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/api/chat'
    | '/diagrams/$id'
    | '/roadmaps/$id'
    | '/share/$token'
    | '/account/'
    | '/dashboard/'
    | '/diagrams/'
    | '/roadmaps/'
    | '/share/diagram/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/api/chat'
    | '/diagrams/$id'
    | '/roadmaps/$id'
    | '/share/$token'
    | '/account'
    | '/dashboard'
    | '/diagrams'
    | '/roadmaps'
    | '/share/diagram/$token'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/api/chat'
    | '/diagrams/$id'
    | '/roadmaps/$id'
    | '/share/$token'
    | '/account/'
    | '/dashboard/'
    | '/diagrams/'
    | '/roadmaps/'
    | '/share/diagram/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiChatRoute: typeof ApiChatRoute
  DiagramsIdRoute: typeof DiagramsIdRoute
  RoadmapsIdRoute: typeof RoadmapsIdRoute
  ShareTokenRoute: typeof ShareTokenRoute
  AccountIndexRoute: typeof AccountIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DiagramsIndexRoute: typeof DiagramsIndexRoute
  RoadmapsIndexRoute: typeof RoadmapsIndexRoute
  ShareDiagramTokenRoute: typeof ShareDiagramTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmaps/': {
      id: '/roadmaps/'
      path: '/roadmaps'
      fullPath: '/roadmaps/'
      preLoaderRoute: typeof RoadmapsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagrams/': {
      id: '/diagrams/'
      path: '/diagrams'
      fullPath: '/diagrams/'
      preLoaderRoute: typeof DiagramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmaps/$id': {
      id: '/roadmaps/$id'
      path: '/roadmaps/$id'
      fullPath: '/roadmaps/$id'
      preLoaderRoute: typeof RoadmapsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagrams/$id': {
      id: '/diagrams/$id'
      path: '/diagrams/$id'
      fullPath: '/diagrams/$id'
      preLoaderRoute: typeof DiagramsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/diagram/$token': {
      id: '/share/diagram/$token'
      path: '/share/diagram/$token'
      fullPath: '/share/diagram/$token'
      preLoaderRoute: typeof ShareDiagramTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiChatRoute: ApiChatRoute,
  DiagramsIdRoute: DiagramsIdRoute,
  RoadmapsIdRoute: RoadmapsIdRoute,
  ShareTokenRoute: ShareTokenRoute,
  AccountIndexRoute: AccountIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DiagramsIndexRoute: DiagramsIndexRoute,
  RoadmapsIndexRoute: RoadmapsIndexRoute,
  ShareDiagramTokenRoute: ShareDiagramTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
